// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64) && linux

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type bpfConnInfoT struct {
	Pid     uint32
	SrcIp   uint32
	DstIp   uint32
	Addrlen uint32
	Fd      uint32
	Sport   uint32
	Dport   uint16
	Family  uint16
	Proto   uint8
	Comm    [64]int8
	_       [3]byte
}

type bpfSockaddr struct {
	SaFamily  uint16
	SaDataMin [14]int8
}

type bpfTraceInfo struct {
	SsrcIP struct {
		SinFamily uint16
		SinPort   uint16
		SinAddr   struct{ S_addr uint32 }
		Pad       [8]uint8
	}
	DdstIP struct {
		SinFamily uint16
		SinPort   uint16
		SinAddr   struct{ S_addr uint32 }
		Pad       [8]uint8
	}
	SrcIP  struct{ S_addr uint32 }
	DstIP  struct{ S_addr uint32 }
	SrcIP6 struct {
		A uint32
		B uint32
		C uint32
		D uint32
	}
	DstIP6 struct {
		A uint32
		B uint32
		C uint32
		D uint32
	}
	Sport   uint16
	Dport   uint16
	Pid     uint32
	Proto   uint32
	Sysexit uint32
	State   uint32
	Family  uint16
	Pad     uint16
	Comm    [32]int8
}

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
	bpfVariableSpecs
}

// bpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	LookUp             *ebpf.ProgramSpec `ebpf:"look_up"`
	TraceRecvfromEnter *ebpf.ProgramSpec `ebpf:"trace_recvfrom_enter"`
	TraceRecvfromExit  *ebpf.ProgramSpec `ebpf:"trace_recvfrom_exit"`
	TraceRecvmsgEnter  *ebpf.ProgramSpec `ebpf:"trace_recvmsg_enter"`
	TraceRecvmsgExit   *ebpf.ProgramSpec `ebpf:"trace_recvmsg_exit"`
	TraceSendmsgEnter  *ebpf.ProgramSpec `ebpf:"trace_sendmsg_enter"`
	TraceSendmsgExit   *ebpf.ProgramSpec `ebpf:"trace_sendmsg_exit"`
	TraceSendtoEnter   *ebpf.ProgramSpec `ebpf:"trace_sendto_enter"`
	TraceSendtoExit    *ebpf.ProgramSpec `ebpf:"trace_sendto_exit"`
	TraceTcpEst        *ebpf.ProgramSpec `ebpf:"trace_tcp_est"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	AddrRecvMap     *ebpf.MapSpec `ebpf:"addrRecv_map"`
	AddrSendMap     *ebpf.MapSpec `ebpf:"addrSend_map"`
	AddrSockNameMap *ebpf.MapSpec `ebpf:"addrSockName_map"`
	ConnInfoMap     *ebpf.MapSpec `ebpf:"conn_info_map"`
	Ipv6Events      *ebpf.MapSpec `ebpf:"ipv6_events"`
	TraceEvents     *ebpf.MapSpec `ebpf:"trace_events"`
}

// bpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfVariableSpecs struct {
	Unused *ebpf.VariableSpec `ebpf:"unused"`
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
	bpfVariables
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	AddrRecvMap     *ebpf.Map `ebpf:"addrRecv_map"`
	AddrSendMap     *ebpf.Map `ebpf:"addrSend_map"`
	AddrSockNameMap *ebpf.Map `ebpf:"addrSockName_map"`
	ConnInfoMap     *ebpf.Map `ebpf:"conn_info_map"`
	Ipv6Events      *ebpf.Map `ebpf:"ipv6_events"`
	TraceEvents     *ebpf.Map `ebpf:"trace_events"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.AddrRecvMap,
		m.AddrSendMap,
		m.AddrSockNameMap,
		m.ConnInfoMap,
		m.Ipv6Events,
		m.TraceEvents,
	)
}

// bpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfVariables struct {
	Unused *ebpf.Variable `ebpf:"unused"`
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	LookUp             *ebpf.Program `ebpf:"look_up"`
	TraceRecvfromEnter *ebpf.Program `ebpf:"trace_recvfrom_enter"`
	TraceRecvfromExit  *ebpf.Program `ebpf:"trace_recvfrom_exit"`
	TraceRecvmsgEnter  *ebpf.Program `ebpf:"trace_recvmsg_enter"`
	TraceRecvmsgExit   *ebpf.Program `ebpf:"trace_recvmsg_exit"`
	TraceSendmsgEnter  *ebpf.Program `ebpf:"trace_sendmsg_enter"`
	TraceSendmsgExit   *ebpf.Program `ebpf:"trace_sendmsg_exit"`
	TraceSendtoEnter   *ebpf.Program `ebpf:"trace_sendto_enter"`
	TraceSendtoExit    *ebpf.Program `ebpf:"trace_sendto_exit"`
	TraceTcpEst        *ebpf.Program `ebpf:"trace_tcp_est"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.LookUp,
		p.TraceRecvfromEnter,
		p.TraceRecvfromExit,
		p.TraceRecvmsgEnter,
		p.TraceRecvmsgExit,
		p.TraceSendmsgEnter,
		p.TraceSendmsgExit,
		p.TraceSendtoEnter,
		p.TraceSendtoExit,
		p.TraceTcpEst,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_x86_bpfel.o
var _BpfBytes []byte
